---
title: "Homework 8"
author: "T.J. Seislove"
date: "3/23/2026"
output:
  html_document:
      code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
library(tidyverse)
library(mosaic)
library(janitor)
library(knitr)
```

# Data Import

```{r}
StudentSurvey <- Lock5Data::StudentSurvey
```

# BMI Calculation & Categorization

```{r}
StudentBMI <- StudentSurvey %>% mutate(
  BMI = 701 * Weight / (Height)^2,
) %>% select(Sex, Height, Weight, BMI)

head(StudentBMI) %>% kable()
```

^[Problem 1 Complete]

```{r}
StudentBMI <- StudentBMI %>% mutate(
  Category = cut(
    BMI, c(-Inf, 18.5, 24.9, 29.9, Inf), labels = c("Underweight", "Healthy Weight", "Overweight", "Obese")
  )
)

head(StudentBMI) %>% kable()
```

^[Problem 2 Complete]

# Highest and Lowest BMIs

```{r}
StudentBMI %>% group_by(Sex) %>% 
  summarize(Low = min(BMI, na.rm = TRUE), High = max(BMI, na.rm = TRUE)) %>% 
  kable()
```

^[Problem 3 Complete]

# SAT Scores

```{r}
StudentSAT <- StudentSurvey %>% 
  mutate(Higher = case_when(
    VerbalSAT > MathSAT ~ "Verbal",
    VerbalSAT < MathSAT ~ "Math",
    VerbalSAT == MathSAT ~ "Equal"
  ), .keep = "used")

head(StudentSAT) %>% kable()
```

^[Problem 4 Complete]

# SAT Z-Scores

```{r}
StudentZ <- StudentSurvey %>% 
  mutate(z_score = (SAT - mean(SAT)) / sd(SAT), .keep = "used")

head(StudentZ) %>% kable()
```

^[Problem 5 Complete]